### ISSUE TITLE
Add support for using sqlx in offline mode

### ISSUE THREAD

**Issue by hdoordt** [mainmatter/gerust#106]
Currently, the Gerust setup only supports query validation with a running database present. That means that even when simply running `cargo check`, or `cargo fmt` fails if the postgres databases are not running and migrated. This gets tedious in development in case of doing a small fix on a branch, which might mean running the migrations a number of times while switching. It's also a pain on CI, where running Rustfmt or Clippy require a running and migrated database.

Sqlx offline mode fixes this, as one would only need to have a running and migrated database present when updating the SQL in the code base, so it'd be great if Gerust supported it.

This would take a small update from sqlx, such that the `prepare` functionality that is currently implemented directly in the `sqlx-cli` binary, could be used from `cli/bin/db`.

**Comment by hdoordt** [comment]
I did some more digging, and I think exposing the prepare functionality from `sqlx` is going to take more work than I thought, and involves significant code duplication. Also `sqlx-cli` is always going to be more complete in both functionality and documentation than `gerust/cli/bin/db`.

It may make more sense to have the latter manage an installation of `sqlx-cli` by having it run `cargo install` if it doesn't exist, and forward commands to the installed `sqlx-cli`

**Comment by marcoow** [comment]
If we can hide `sqlx-cli` within gerust somehow, that might be fine but I'd say the hard requirements for gerust are

* no additional requirements besides a working Rust toolchain to be able to use gerust
* developer only works with gerust's own binaries db and generate (maybe others later)
* we should be able to have consistent terminal output, coloring, formatting, etc. – we can't have different styles of output for e.g. `generate` and DB handling stuff that's offloaded to `sqlx-cli`

**Comment by hdoordt** [comment]
@marcoow thanks for the details. I had a stab at it and opened PR #115

**Comment by hdoordt** [comment]
Fixed with #115
