### ISSUE TITLE
Use CARGO_MANIFEST_DIR to find path to migrations folder

### ISSUE THREAD

**Issue by hdoordt** [mainmatter/gerust#108]
The `cargo db migrate` command does not work when called from a folder within the Gerust-generated project other than the root. Its location is [hard coded](https://github.com/mainmatter/gerust/blob/main/blueprint/cli/src/bin/db.rs#L155).

Using the [`CARGO_MANIFEST_DIR`](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates), ensure that the migrations folder is discovered relatively to the location of the `Cargo.toml`, so the application does not need to assume from where the command gets called.

**Comment by hdoordt** [comment]
@oliverbarnes Would you like to implement this one? I'd be happy to help out if you need pointers (no pun intended)

**Comment by oliverbarnes** [comment]
@hdoordt I would! But need to carveout time for it, I hope I'm not blocking anything
