### ISSUE TITLE
Fix db drop

### ISSUE THREAD

**Issue by oliverbarnes** [mainmatter/gerust#124]
While testing out #123, I noticed that `cargo db drop` (and `reset`, by consequence) isn't working. 

I couldn't immediately tell why due to the laconic error messages, which I know are an known issue :)

I'm using a super user postgres role with the name of the generated app.

**Comment by hdoordt** [comment]
@oliverbarnes Can you try it with either the latest revision of Gerust or with the `--debug` flag enabled (`cargo db drop --debug`) and past the error message?

**Comment by oliverbarnes** [comment]
Works well now 🚀 drops the db when present, and presents a nice message when not.
